### ISSUE TITLE
invalid License key

### ISSUE THREAD

**Issue by Akila3** [ozh/yourls-geoip-update#1]
Database not updated.
Error downloading "GeoLite2-Country". Invalid license key.

when I try generating a key it asks me:
ld versions of our [GeoIP Update](https://dev.maxmind.com/geoip/updating-databases?lang=en) program use a different license key format. Will this key be used for GeoIP Update? Yes / No

I selected "Yes", than it asks me :
Generate a license key and config file for use with geoipupdate version 3.1.1 or newer.
or
Generate a license key and config file for use with geoipupdate versions older than 3.1.1.
This key will be stored in an unhashed format.

i tried all options and all give me error on your plugin that key is invalid.
which one should I use?

**Comment by ozh** [comment]
The key is not to be used with their GeoIP Update program ... It's to be used with this plugin.... so the answer to the first question is "no".

**Comment by Akila3** [comment]
I selected "no" and still getting the same error:
Database not updated.
Error downloading "GeoLite2-Country". Invalid license key.
is there a way to debug it?

the license key I generated from here:
https://www.maxmind.com/en/accounts/{xxxxxxxx}/license-key
